services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - my_event_network
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - my_event_network
    depends_on:
      - backend
networks:
  my_event_network:
